#! /bin/bash

# mpd

clear
svn up ./mpd-spec.xml
svn up ~/working/mpd3/xsd/mpd-catalog-3.0.xsd
# cp ~/working/mpd3/xsd/mpd-catalog-3.0.xsd ~/working/mpd3/mpd-toolkit-3.0/
make clean
make all
svn ci -m "new" ./mpd-spec.html
svn ci -m "new" ./mpd-spec.txt
# cp mpd-spec.html mpd-toolkit-3.0/mpd-spec-3.0.html

