#!/bin/bash

# validate meta

xmllint --noout meta/manifest.xml
xmllint --noout meta/manifest/xml-catalog.xml
xmllint --noout meta/manifest/manifest.xsd
xs-validate -c manifest/xml-catalog.xml manifest.xml
