#!/bin/bash

set -o pipefail -o errexit -o nounset

fail () {
     printf 'ERROR: %s\n' "$*" >&2
     exit 1
}

OPTIND=1
while getopts :p option
do case "$option" in
       p ) # set limited path
           export PATH=/bin:/usr/bin:/opt/local/bin:./tmp/root/bin;;
       : ) # getops reporting missing argument
           printf "Short option \"%s\" missing argument" "$OPTARG" >&2
           exit 1;;
   esac
done
shift $((OPTIND-1))

(( $# > 0 )) || fail "need a command"

command=$1
shift
case $command in
     configure ) # re-run configure with current parameters
         /opt/local/bin/gmake -C . -f configure.mk
         ./configure install_dir="@install_dir@"
         ;;
     install ) # install safely and fast
         /opt/local/bin/gmake -C . -j dependencies.mk
         /opt/local/bin/gmake -C . -j 
         /opt/local/bin/gmake -C . -j install
         ;;
     open-html | oh )
         make -j ./dependencies.mk depend=true
         make -j ./tmp/niem-iepd-spec.html
         open ./tmp/niem-iepd-spec.html
         ;;
     clean )
         make clean depend=no
         ;;
     publish )
         rm -rf ./tmp/publish-checkout
         current_branch=$(git -C @install_dir@ rev-parse --abbrev-ref HEAD)
         git -C ./tmp clone --branch gh-pages https://github.com/NIEM/MPD-Spec.git publish-checkout
         rm -rf ./tmp/publish-checkout/"$current_branch"
         git -C @install_dir@ publish -d /Users/wr/r/niem/mpd-spec/source/tmp/publish-checkout "$current_branch"
         echo "That's as far as it gets for now. Add to it when you have new content."
         exit 1
         ;;
     * ) fail "Unknown command \"$command\""
    ;;
esac
